AWSTemplateFormatVersion: 2010-09-09
Description: 'This template builds a basic linux EC2 instance and installs a Geth node on it'

Parameters:
  KeyNameParam:
    Description: EC2 Instance SSH Key
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceTypeParam:
    Description: EC2 instance specs configuration
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium

Mappings:
  AMIs:
    eu-west-1:
      Name: ami-9cbe9be5

Resources:

  EC2Instance:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !FindInMap [ AMIs, !Ref 'AWS::Region', Name]
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref KeyNameParam
      SecurityGroupIds: 
        - !ImportValue EC2SecurityGroupSSHGroupIdOut
      SubnetId: !ImportValue EC2Subnet1Out
      Tags:
        - Key: Name
          Value: Geth Node
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            sudo yum install -y golang
            sudo yum install -y gmp-devel
            cd /home/ec2-user
            git clone https://github.com/ethereum/go-ethereum
            cd go-ethereum/
            make geth
